---
title: "Assignment2b"
author: "Xin Li"
date: "2/22/2020"
output:
  html_document: default
  pdf_document: default
---

## Assignment2b 
Define Secant Method
```{r}
library(shape)
Secant<-function(func,x0, x1,Tolerance,MaxNumberOfIterations,DrawLines){
#initialize  Deviation to record |f(x)| that is large enough. 
  Deviation <- 1000
  #Set up a counter, i, to record how many iterations you have performed. Set it equal to 0	
  i <- 0
  # Initialize the values of X0 and X1 
  x0 <- 1
  x1 <- 2

  #Set up a while loop until we hit the required target accuracy or the max number of steps
  while ((i<MaxNumberOfIterations)&&(Deviation>Tolerance))
  {
    y0 <- func(x0)
    y1 <- func(x1)

    if ((y0=="NaN")||(y1=="NaN")){
      cat("\nFunction or derivative not defined error.\n")
      break
    }
    if (DrawLines){
      Arrows(x0,0,x0,y0,col="blue",lty=2,arr.length=0.01, arr.type = "T")
      Arrows(x1,0,x1,y1,col="blue",lty=2,arr.length=0.01, arr.type = "T")
      }
    
    #Find the next X-value using Secant formula. 
    x2 <- x1 - y1*(x0-x1)/(y0-y1)
    x0 <- x1
    x1 <- x2
    y2 <- func(x2)
    # calculate Deviation<- |f(x)-0|
    Deviation <- abs(y2)
    # increase the value of your iteration counter
    i <- i+1
    
    # if you like, have the program write out how it is getting on
    cat(paste("\nIteration ",i,":   X=",x1,"  Y=",y2))
    
    # If you are feeling fancy, add some line segments to the screen to show where it just went
    # See the 'fixed points' code for a reminder of how to do that.
    # output the result
    if (Deviation<Tolerance){
      cat(paste("\nFound the root point: ",x1, " after ", i, "iterations"))
    }else{
      cat(paste("\nConvergence failure. Deviation: ",Deviation, "after ", i, 	"iterations"))} 
  }
  
  
  # have the function return the answer
  return(x1)
}

F2 <- function(z){
  return(log(z)-exp(-z))
}

```

Define Newton-Raphson function
```{r}
library(shape)
NewtonRaphson<-function(func,StartingValue,Tolerance,MaxNumberOfIterations,DrawLines){
  #initialize a variable, Deviation (say), to record |f(x)| so that you know how far away you are from 0. 
  #(So initialize it to some arbitrary large number)
  Deviation <- 1000
  #Set up a counter, i, to record how many iterations you have performed. Set it equal to 0	
  i <- 0
  # Initialize the values of x and f(x)
  X  <- StartingValue
  
  #Set up a while loop until we hit the required target accuracy or the max. number of steps
  Z <- c()
  while ((i<MaxNumberOfIterations)&&(Deviation>Tolerance))
  {
    # Record the value of f(x) and f’(x), for the current x value. 
    Xprime <- func(X)
    Z[1] <- Xprime[1]
    Z[2] <- Xprime[2]
    X_1 <- X - Z[1]/Z[2] #To draw line segment for Xn+1
    # I put them in a variable Z. Z[1]<-f(x); Z[2]<-f’(x)
    # To be safe, check that the function and it's derivative are defined at X (either could be NaN if you are unlucky)
    if ((Z[1]=="NaN")||(Z[2]=="NaN")){
      cat("\nFunction or derivative not defined error.\n")
      break
    }
    if (DrawLines){
      Arrows(X,0,X,Z[1],col="blue",lty=2,arr.length=0.01, arr.type = "T")
      Arrows(X,Z[1],X_1,0,col="blue",lty=2,arr.length=0.01, arr.type = "T")
      }
    
    #Find the next X-value using Newton-Raphson's formula. Let's call that value X
    X <- X - Z[1]/Z[2]
    Y <- func(X)[1]
    # calculate Deviation<- |f(x)-0|
    Deviation <- abs(Z[1]-0)
    # increase the value of your iteration counter
    i <- i+1
    
    # if you like, have the program write out how it is getting on
    cat(paste("\nIteration ",i,":   X=",X,"  Y=",Y))
    
    # If you are feeling fancy, add some line segments to the screen to show where it just went
    # See the 'fixed points' code for a reminder of how to do that.
    # output the result
    if (Deviation<Tolerance){
      cat(paste("\nFound the root point: ",X, " after ", i, "iterations"))
    }else{
      cat(paste("\nConvergence failure. Deviation: ",Deviation, "after ", i, 	"iterations"))} 
  }
  
  
  # have the function return the answer
  return(X)
}
```


## Function cos(x)-x
```{r warning=F}
par(mfrow = c(1,2),oma = c(0,0,3,0))

#Secant Method
F1 <- function(z){
  return(cos(z)-z)
}
curve(cos(x)-x,-1,2,main="Secant:y=cos(x)-x")
Secant(F1,1,2,1e-3,40,1)
abline(h=0, col="red", lty=2)

#Newton-Raphson function
F1_prime <- function(z){
  return(c(cos(z)-z, -sin(z)-1))
}
curve(cos(x)-x,-1,2,main="Newton-Raphson:y=cos(x)-x")
NewtonRaphson(F1_prime,3,1e-3,40,1)
abline(h=0, col="red", lty=2)
```


## Function log(x)-exp(-x)
```{r warning=F}
par(mfrow = c(1,2),oma = c(0,0,3,0))
#Secant Method
F2 <- function(z){
  return(log(z)-exp(-z))
}
curve(log(x)-exp(-x),-1,2,main="Secant:y=log(x)-exp(-x)")
Secant(F2,1,2,1e-3,40,1)
abline(h=0, col="red", lty=2)

#Newton-Raphson function
F2_prime <- function(z){
  return(c(log(z)-exp(-z), (1/z)+exp(-z)))
}
curve(log(x)-exp(-x),-1,2,main="Newton-Raphson:log(x)-exp(-x)")
NewtonRaphson(F2_prime,3,1e-3,40,1)
abline(h=0, col="red", lty=2)
```



